language: erlang

notifications:
  disabled: true

install:
  - wget http://www.quviq.com/downloads/eqcmini.zip
  - unzip eqcmini.zip
  - export ERL_LIBS=eqcmini

script: 
  - make deps_eunit 
  - make eunit
  - |
     if [$TRAVIS_OTP_RELEASE == "17.0"]
      then 
        make dialyzer
     fi


otp_release:
   - 17.0
   - R16B03-1
   - R16B02
   - R16B01
   - R15B03
   - R15B02
   - R15B01
   - R14B04
   - R14B03
   - R14B02
